version: "2"
services:
  postgres:
    image: postgres
    volumes:
      - ../clinical-data-workflow/workflows/psql_init/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "2345:5432"
  r2rml:
    image: registry.gitlab.com/um-cds/fair/tools/r2rml:1.0
    links:
      - postgres:dbhost
      - graphdb:graphdb
  notebook:
    image: jvsoest/fair-jupyter
    ports:
      - "8888:8888"
      - "8088:8088"
    # volumes:
    #   - ./notebooks:/queries/
    links:
      - postgres:postgresdb
      - graphdb:graphdb
  graphdb:
    build:
      context: ./graphdb
    ports: 
      - "7200:7200"
    environment:
      - GDB_HEAP_SIZE=2g
      - GDB_MIN_MEM=1g
      - GDB_MAX_MEM=2g
  ctp:
    image: jvsoest/ctp
    ports:
      - "8081:8081"
      - "104:104"
    links:
      - lidicom:lidicom
    volumes:
      - ./ctp/config.xml:/CTP/config.xml
      - ./ctp/ctpConfig:/CTP/ctpConfig
  lidicom:
    image: registry.gitlab.com/um-cds/projects/covid-19/import-to-rdf:lidicom
    links:
      - graphdb:graphdb
    volumes:
      - ./lidicom/config.json:/app/config.json
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.169.230.1/24
